swagger: '2.0'
info:
  title: 'Business Automation Opportunity Explorer APIs'
  description: 'Set of micro-services for representation learning of process data, descriptive analysis for hotspots,
                prescriptive analysis for automation opportunities and what-if analysis for KPI impact'
  version: 1.0.0
host: 'localhost:3000'
schemes:
  - https
basePath: /baox/v1
produces:
  - application/json
paths:
  /mine_bpmn_model:
    post:
      summary: Mine BPMN model from event log with structured and unstructured data
      description: >
        Mine BPMN model from event log with structured and unstructured data
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: eventlog
          in: formData
          description: event log to upload
          required: true
          type: file
        - name: caseid
          in: formData
          description: case id field name in the event log
          required: true
          type: string
        - name: activity
          in: formData
          description: activity field name in the event log
          required: true
          type: string
        - name: timestamp
          in: formData
          description: activity completion timestamp in event log
          required: true
          type: string
        - name: comments
          in: formData
          description: comments field name in the event log
          required: false
          type: string
      tags:
        - Representation learning
      responses:
        '202':
          description: OK
          schema:
            type: json

  /mine_pn_model:
    post:
      summary: Mine Petrinet model from event log with structured data
      description: >
        Mine Petrinet model from event log with structured data
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: eventlog
          in: formData
          description: event log to upload
          required: true
          type: file
        - name: caseid
          in: formData
          description: case id field name in the event log
          required: true
          type: string
        - name: activity
          in: formData
          description: activity field name in the event log
          required: true
          type: string
        - name: timestamp
          in: formData
          description: activity completion timestamp in event log
          required: true
          type: string
      tags:
        - Representation learning
      responses:
        '202':
          description: OK
          schema:
            type: json
            
  /convert_to_pnml:
    post:
      summary: Convert BPMN model into Petrinet model
      description: >
        convert bpmn model into petrinet model
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: bpmn_model_file
          in: formData
          description: bpmn model to upload
          required: true
          type: file
      tags:
        - Representation learning
      responses:
        '202':
          description: OK
          schema:
            type: json

  /learn_trie_representation:
    post:
      summary: learn trie representation from activity timeseries
      description: >
        learn trie representation from activity timeseries
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: activity_timeseries
          in: formData
          description: activity_timeseries from BAI
          required: true
          type: file
      tags:
        - Representation learning
      responses:
        '202':
          description: OK
          schema:
            type: json

  /convert_to_dfg:
    post:
      summary: Convert BPMN model into Directly follows graph representation
      description: >
        Convert BPMN model into Directly follows graph representation
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: bpmn_model_file
          in: formData
          description: bpmn model to upload
          required: true
          type: file
      tags:
        - Representation learning
      responses:
        '202':
          description: OK
          schema:
            type: json

definitions:
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
