swagger: '2.0'
info:
  title: 'Business Automation Opportunity Explorer APIs'
  description: 'Set of micro-services for representation learning of process data, descriptive analysis for hotspots,
                prescriptive analysis for automation opportunities and what-if analysis for KPI impact'
  version: 1.0.0
host: 'localhost:3000'
schemes:
  - https
basePath: /baox/v1
produces:
  - application/json
paths:
  /mine_bpmn_model:
    post:
      summary: Mine BPMN model from event log with structured and unstructured data
      description: >
        Mine BPMN model from event log with structured and unstructured data
      produces:
        - application/xml
      consumes:
        - multipart/form-data
      parameters:
        - name: eventlog
          in: formData
          description: event log to upload
          required: true
          type: file
        - name: caseid
          in: formData
          description: case id field name in the event log
          required: true
          type: string
        - name: activity
          in: formData
          description: activity field name in the event log
          required: true
          type: string
        - name: timestamp
          in: formData
          description: activity completion timestamp in event log
          required: true
          type: string
        - name: comments
          in: formData
          description: comments field name in the event log
          required: false
          type: string
      tags:
        - Representation learning
      responses:
        '200':
          description: Process model in BPMN2.0 format
          content:
            application/xml:

  /mine_pn_model:
    post:
      summary: Mine Petrinet model from event log with structured data
      description: >
        Mine Petrinet model from event log with structured data
      produces:
        - application/xml
      consumes:
        - multipart/form-data
      parameters:
        - name: eventlog
          in: formData
          description: event log to upload
          required: true
          type: file
        - name: caseid
          in: formData
          description: case id field name in the event log
          required: true
          type: string
        - name: activity
          in: formData
          description: activity field name in the event log
          required: true
          type: string
        - name: timestamp
          in: formData
          description: activity completion timestamp in event log
          required: true
          type: string
      tags:
        - Representation learning
      responses:
        '200':
          description: Process model in PNML format
          content:
            application/xml:

  /convert_to_pnml:
    post:
      summary: Convert BPMN model into Petrinet model
      description: >
        convert bpmn model into petrinet model
      produces:
        - application/xml
      consumes:
        - multipart/form-data
      parameters:
        - name: bpmn_model_file
          in: formData
          description: bpmn model to upload
          required: true
          type: file
      tags:
        - Representation learning
      responses:
        '200':
          description: Process model in PNML format
          content:
            application/xml:

  /learn_trie_representation:
    post:
      summary: learn trie representation from activity timeseries
      description: >
        learn trie representation from activity timeseries
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: activity_timeseries from BAI
          required: true
          type: file
      tags:
        - Representation learning
      responses:
        '200':
          description: Trie representation in graphML format
          content:
            application/xml:


  /convert_to_dfg:
    post:
      summary: Convert BPMN model into Directly follows graph representation
      description: >
        Convert BPMN model into Directly follows graph representation
      produces:
        - application/xml
      consumes:
        - multipart/form-data
      parameters:
        - name: bpmn_model_file
          in: formData
          description: bpmn model to upload
          required: true
          type: file
      tags:
        - Representation learning
      responses:
        '200':
          description: DFG in graphML format
          content:
            application/xml:

  /get_unique_paths:
    post:
      summary: get unique paths from activity timeseries
      description: >
        get unique paths taken along with summary from activity time series
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: activity_timeseries from BAI
          required: true
          type: file
      tags:
        - Descriptive Analysis for Hotspots
      responses:
        '200':
          description: paths in json format
          content:
            application/json:
  /replay_log_on_dfg:
    post:
      summary: Replay activity timeseries on Directly follows graph for performance analysis
      description: >
        Replay activity timeseries on Directly follows graph for performance analysis
      produces:
        - application/xml
      consumes:
        - multipart/form-data
      parameters:
        - name: activity_timeseries_file
          in: formData
          description: activity_timeseries from BAI
          required: true
          type: file
        - name: dfg_file
          in: formData
          description: Directly follows graph of the model
          required: true
          type: file
      tags:
        - Descriptive Analysis for Hotspots
      responses:
        '200':
          description: Decorated DFG with performance annotations
          content:
            application/json:


definitions:
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
